<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK4m2aua\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK4m2aua/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerK4m2aua.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerK4m2aua\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerK4m2aua\appDevDebugProjectContainer([
    'container.build_hash' => 'K4m2aua',
    'container.build_id' => '5d30f11c',
    'container.build_time' => 1617029260,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK4m2aua');
